### ISSUE TITLE
Wireframes Interativos

### ISSUE THREAD

**Issue by Maia2098** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t4-coincontrol#11]
@g413rie1 , proceder conforme falamos em reunião.

**Comment by g413rie1** [comment]
![wireframes CoinControl](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t4-coincontrol/assets/127675409/1b836004-e23c-4b99-8ab8-df33d0c5009e)

**Comment by Maia2098** [comment]
@g413rie1 , considerando que o design das telas é com pensamento nos usuários, com base no nosso atual pensamento sobre o projeto, acredito que você já pode comitar a imagem dentro do repositório. 

Acho melhor fazer o commit como imagem e não link (como semestre passado).

**Comment by Maia2098** [comment]
Incluído no repositório.
