### ISSUE TITLE
Projeto da Base de Dados

### ISSUE THREAD

**Issue by Maia2098** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t4-coincontrol#12]
@TiagoAraujo12 , proceder conforme falado em reunião.
Link de auxílio: https://www.ibm.com/docs/en/cognos-analytics/11.0.0?topic=designer-creating-relational-model

**Comment by TiagoAraujo12** [comment]
Modelo inicial criado com base no diagrama de classe.

Caso seja alterado e inserido novas informações no diagrama, esse modelo deverá ser alterado. 

![Image](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t4-coincontrol/assets/125419720/d8dee1bc-6fed-4622-b841-d3d226f69f23)
[Relacionamento.pdf](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t4-coincontrol/files/12641374/Relacionamento.pdf)

**Comment by Maia2098** [comment]
Validar com o Professor se isso não seria o Projeto da Base de Dados.

**Comment by Maia2098** [comment]
@TiagoAraujo12 , fazer as alterações conforme orientações do Professor e a nossa conversa. Eu alterei esse issue para Projeto da Base de Dados. 

Vou alterar o nome do da Ana também.

**Comment by TiagoAraujo12** [comment]
Novo projeto com base no novo diagrama de classe

[BancoDeDados2.pdf](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t4-coincontrol/files/12704908/BancoDeDados2.pdf)



.

**Comment by Maia2098** [comment]
Feito.
