### ISSUE TITLE
Modelo Entidade Relacionamento (Projeto Conceitual)

### ISSUE THREAD

**Issue by Maia2098** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t4-coincontrol#13]
@Ana-MP , esse entregável em particular, iremos validar com o Professor na aula de quarta sobre como devemos proceder.

**Comment by Maia2098** [comment]
Deve ter chave primária

**Comment by Ana-MP** [comment]
![Image](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t4-coincontrol/assets/75648729/b3188eb0-8989-4da5-ab7a-5eabb2a2294c)

**Comment by Maia2098** [comment]
Validar amanhã se, na verdade, não se trata do Projeto Conceitual.

**Comment by Maia2098** [comment]
@Ana-MP , após assistir o vídeo da aula, verificar as classes elaboradas pelo @TiagoAraujo12 para atualização do Modelo.

Eu alterei o nome desse issue vez que é o Modelo Entidade Relacionamento (Projeto Conceitual) e não o projeto da base de dados.

**Comment by Ana-MP** [comment]
[Modelo Relacional  coincontrol.pdf](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t4-coincontrol/files/12705631/Modelo.Relacional.coincontrol.pdf)

**Comment by Maia2098** [comment]
Incluído.
