### ISSUE TITLE
Plano de Testes de Software

### ISSUE THREAD

**Issue by Maia2098** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t4-coincontrol#14]
@ChrisCuri , gentileza proceder com o plano de testes de software tendo, como base, o template fornecido pela faculdade.

**Comment by Maia2098** [comment]
Validar com o Professor se o campo "passos" pode continuar como "A FAZER".

**Comment by Maia2098** [comment]
@ChrisCuri , fazer uma última revisão do plano de testes. Só verificar se estamos ok com os requisitos testáveis.

**Comment by ChristianeCuri** [comment]
Plano de testes revisado. Somente os campos "Passos" permanecem em aberto para completarmos a informação quando estivermos na etapa de desenvolvimento.

**Comment by Maia2098** [comment]
Perfeito.
