### ISSUE TITLE
Criação do Banco de Dados

### ISSUE THREAD

**Issue by Maia2098** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t4-coincontrol#23]
Proceder conforme discutido em reunião.

**Comment by TiagoAraujo12** [comment]
Banco de dados no azure criado:

Banco: CoinControl

Servidor: coincontrol-prod.database.windows.net

Modelo de conexão: azure active directory

**Comment by Maia2098** [comment]
Comentários do Professor: Seriam só as quatro tabelas mesmo visto nosso diagrama de classes.

Nosso bd está batendo com as informações da etapa 2.

**Comment by Maia2098** [comment]
Na nossa reunião de terça, podemos discutir a questão do banco de dados, @TiagoAraujo12 , se vamos usar local para essa etapa.

**Comment by Maia2098** [comment]
Vou fechar o issue depois da entrega no domingo.

**Comment by Maia2098** [comment]
Tarefa vencida.
