### ISSUE TITLE
Elaboração de end point do front para o back - CRUD do usuário

### ISSUE THREAD

**Issue by Maia2098** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t4-coincontrol#24]
Levar em consideração o banco de dados conforme falamos em reunião.

**Comment by Maia2098** [comment]
@Jonathan-Rocha , olhar o que coloquei na criação do usuário.

**Comment by Jonathan-Rocha** [comment]
@Maia2098 , olhei aqui e acredito que no formulario de login, não precisa do campo "nome", pois estamos fazendo a verificação do login de acordo com email e senha. O formulário de criação está ok. E a view de detalhes não precisa de mostrar a senha.

**Comment by Maia2098** [comment]
Feito. Precisamos conectar com o banco de dados agora.

**Comment by Maia2098** [comment]
Vou fechar o issue depois da entrega no domingo.

**Comment by Maia2098** [comment]
Tarefa vencida.
