### ISSUE TITLE
Criação da Carteira no Banco de Dados

### ISSUE THREAD

**Issue by Maia2098** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t4-coincontrol#25]
Ana e Cristiane procederem com a criação conforme falamos em reunião levando em consideração as funcionalidades da classe.

**Comment by Maia2098** [comment]
Fazer a conexão com o banco de dados criado pelo @TiagoAraujo12

**Comment by Maia2098** [comment]
@Ana-MP e @ChrisCuri como estamos nessa tarefa?

**Comment by Maia2098** [comment]
@Ana-MP e @ChrisCuri , conseguiremos implementar o view da carteira?

**Comment by Maia2098** [comment]
@Ana-MP e @ChrisCuri , posteriormente confirmarem quais foram as implementações.
Fizemos a transação também, correto?

**Comment by ChristianeCuri** [comment]
Iniciei a confecção da transação mas ainda não concluí, darei continuidade na próxima semana visando entregarmos na etapa 4.

**Comment by Maia2098** [comment]
Será reaproveitado na etapa 4.
Nome será alterado na reunião de hoje.

**Comment by Ana-MP** [comment]
Eu fiz a controle e model. Esse final de semana pretendo  terminar a view e fazer os testes se a implementação ficou OK.

**Comment by Maia2098** [comment]
@Ana-MP , proceder conforme a nossa reunião com a view da carteira.

**Comment by Maia2098** [comment]
@Ana-MP , eu acho que seria interesse já termos isso para reunião de quarta-feira com o professor, conseguiu finalizar?

**Comment by Maia2098** [comment]
Feito e rodando.
