### ISSUE TITLE
Atualizar ER conforme o Diagrama de Classes

### ISSUE THREAD

**Issue by Maia2098** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t4-coincontrol#27]
@Ana-MP , conforme o novo diagrama de classes, atualizar o nosso ER.

**Comment by Maia2098** [comment]
@Ana-MP , lembrar de atualizar o ER ainda para essa etapa.

**Comment by Maia2098** [comment]
@Ana-MP , lembrando do prazo de entrega.
Atualizar o nosso ER conforme novo diagrama de classes e projeto do banco de dados.
item 05 - arquitetura da solução

**Comment by Ana-MP** [comment]
[Diagrama  ER coincontrol.drawio.pdf](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t4-coincontrol/files/13064363/Diagrama.ER.coincontrol.drawio.pdf)
Diagrama atualizado de acordo com as modificações acordadas.

**Comment by Maia2098** [comment]
Tarefa vencida.
