### ISSUE TITLE
Hospedar a aplicação no Azure

### ISSUE THREAD

**Issue by Maia2098** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t4-coincontrol#28]
O banco de dados já está criado, logo precisamos, nessa etapa, hospedar a aplicação na nuvem.

https://learn.microsoft.com/pt-br/azure/developer/intro/hosting-apps-on-azure

**Comment by Maia2098** [comment]
@TiagoAraujo12 , caso o limite de cem dólares não seja suficiente eu faço a licença.

**Comment by Maia2098** [comment]
@TiagoAraujo12 , tivemos algum progresso na tarefa?

**Comment by TiagoAraujo12** [comment]
Aplicação hospeda.

Link: https://coincontrolpuc.azurewebsites.net/

**Comment by Maia2098** [comment]
Testei aqui e funcionou.
Muito bom!!

**Comment by Maia2098** [comment]
@Maia2098 , printar e colocar nos testes.

**Comment by Maia2098** [comment]
Hospedada e já inserida nos testes.
