### ISSUE TITLE
Atualizar documentação github

### ISSUE THREAD

**Issue by Maia2098** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t4-coincontrol#6]

**Comment by Maia2098** [comment]
@g413rie1 , terminei de verificar as informações do repositório. Consegue dar uma última validada para o envio?

**Comment by Maia2098** [comment]
@g413rie1 documento em word e PDF.


[Etapa 1 - CoinControl - 03 - 09.pdf](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t4-coincontrol/files/12507687/Etapa.1.-.CoinControl.-.03.-.09.pdf)
[Etapa 1 - CoinControl - 03 - 09.docx](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t4-coincontrol/files/12507688/Etapa.1.-.CoinControl.-.03.-.09.docx)

**Comment by g413rie1** [comment]
> @g413rie1 , terminei de verificar as informações do repositório. Consegue dar uma última validada para o envio?

Texto revisado, liberado para envio.

**Comment by Maia2098** [comment]
Enviado. 

![Image](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t4-coincontrol/assets/100796561/80240431-3f54-421c-9c63-c655dfe7edd1)

**Comment by Maia2098** [comment]
Backlog da etapa:



![Image](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t4-coincontrol/assets/100796561/af219063-84e2-434f-b61a-931ff23ba33e)

**Comment by Maia2098** [comment]
![Image](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t4-coincontrol/assets/100796561/70e30390-729a-413e-a80a-9bb7fecc7a17)

**Comment by Maia2098** [comment]
![Image](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t4-coincontrol/assets/100796561/2e5f4cb5-302b-4e87-a431-e9e03ab4c052)
