### ISSUE TITLE
Diagrama de Classes

### ISSUE THREAD

**Issue by Maia2098** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t4-coincontrol#9]
@TiagoAraujo12 , proceder conforme falado em reunião. Buscar, se possível, esboço para próxima quarta-feira.

**Comment by TiagoAraujo12** [comment]
Segue PDF e arquivo do software Astah que foi utilizado para criar o diagrama.


[DiagramadeClasse.pdf](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t4-coincontrol/files/12641166/DiagramadeClasse.pdf)

**Comment by Maia2098** [comment]
@TiagoAraujo12 , fazer as alterações conforme orientações do Professor e a nossa conversa.

**Comment by TiagoAraujo12** [comment]
Novo diagrama criado de acordo com a reunião com professor.

[DiagramadeClasse2.pdf](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t4-coincontrol/files/12704911/DiagramadeClasse2.pdf)

**Comment by Maia2098** [comment]
Incluído.
